### ISSUE TITLE
If the connection to PG fails during execution, it will cause the program to crash (infinite loop)

### ISSUE THREAD

**Issue by VxRain** [kysely-org/kysely-postgres-js#60]
**Env:**
* Win10
* Node v20.14.0
* kysely: 0.27.3
* kysely-postgres-js: 2.0.0,
* postgres: 3.4.4

---

**Reproduction steps:**

1. Start the PostgreSQL service.
2. Start the application.
3. Kill the PostgreSQL process.
4. The error repeats infinitely.

```js
import { Kysely } from "kysely";
import { PostgresJSDialect } from "kysely-postgres-js";
import postgres from "postgres";

// listen for unhandledRejection and uncaughtException
process.on("unhandledRejection", (reason) => {
  console.error("unhandledRejection: ", reason);
});
process.on("uncaughtException", (err) => {
  console.error("uncaughtException: ", err);
});

const pg = postgres({
  host: "localhost",
  max: 10,
  port: 5432,
  database: "test",
  user: "test",
  password: "test",
});
const db = new Kysely({ dialect: new PostgresJSDialect({ postgres: pg }) });

async function main() {
  await pg`SELECT 1`; // check connection

  setInterval(async () => {
    const user = await db
      .selectFrom("User")
      .select("username")
      .where("id", "=", 1)
      .executeTakeFirstOrThrow();
    console.log(Date.now(), user);
  }, 1000);
}
main();

```

**Error logs:**
```
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
uncaughtException:  TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:389:48)
    at errored (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:384:17)
    at Socket.error (file:///C:/Users/Administrator/Desktop/Workspace/kysely-postgres/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:376:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
    
**Additionally, I found that if the connection to PostgreSQL fails when app start, the Kysely instance initializes normally, but executing a query throws an error: `"Cannot read properties of undefined (reading 'replace')."`**

Related to #9, #10, #11, I think we should investigate further to resolve the related issues.

**Comment by VxRain** [comment]
I don't think this is an issue with Postgres.js. I also tested it using Postgres.js. After killing the PG process, Postgres.js correctly throws an error and attempts to reconnect. Once the reconnection is successful, the program outputs results correctly, which is the expected behavior.

**Comment by VxRain** [comment]
@joshxyzhimself 

Hi, I didn't encounter this issue when using only Postgres.js. Does this problem occur only when using the Docker image? Could you provide a minimal reproducible code or repository?

**Comment by VxRain** [comment]
@joshxyzhimself Yes, we are encountering the same issue.

Currently, we can use
```js
process.on("uncaughtException", (err) => {
  console.error("uncaughtException: ", err);
});
```
to catch the error. But in this case, it isn't very helpful because it keeps throwing errors in an infinite loop, blocking the main process and making the service completely unusable. I think this might need a thorough investigation @igalklebanov

**Comment by igalklebanov** [comment]
Hey 👋 

This happens in `postgres.js` when using the `reserve()` method. See https://github.com/porsager/postgres/issues/778#issuecomment-2154846646.

For now, you can extend this library's dialect, and override the driver's `acquireConnection` method with a retry mechanism around the `.reserve()` invocation.

Alternatively, don't execute with Kysely for now, but compile and pass the compiled queries straight to `postgres.js`'s `unsafe` method.

**Comment by igalklebanov** [comment]
> Found this issue upstream, they're using mssql but similar problem where app crashes when db unreachable.
> 
> [kysely-org/kysely#836](https://github.com/kysely-org/kysely/issues/836)

Not the same.

`kysely` core uses `tedious`, not `mssql`, as the underlying driver for `MssqlDialect`.

Unlike `postgre.js`, `tedious` doesn't come with connection pool management, so we're using `tarn.js` (also used by `mssql` and `knex`) for pool management. 

The issue there was `tedious` throwing connection errors asynchronously if you don't subscribe to `Connection`'s "error" events, causing uncaught exceptions.

**Comment by piekczyk** [comment]
For those who have this problem still unresolved - in my case I forgot to destroy db instance after each call, so requests were creating a new clients each time. Once max client threshold was reached it failed with this ugly error:

```Cannot read properties of undefined (reading 'replace') ...```
